version: "3"
services:
  auth-proxy:
  password:
    build: ./docker/${CONTAINER}
    image: ${ORGANIZATION}/${CONTAINER}:${BUILD_TAG}
    container_name: ${CONTAINER}
    restart: always
    ports:
      - "3000:3000"
    networks:
      - overlay

networks:
    overlay:
