replicaCount: 3
vault:
  address: http://vault-vault.vault:8200
image:
  repository: celliott/password
  tag: latest
  pullPolicy: Always
service:
  name: password
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000
ingress:
  enabled: false
  auth: https://auth.toobox.io
  hostname:
  tls:
    enabled: true
resources: {}
